### ISSUE TITLE
Sampler hangs when configuring with Ansible

### ISSUE THREAD

**Issue by Brian-Tehan** [preese/perfSONAR-Sampler#6]
Hello Phil,

I've setup the sampler twice now on a spare PC but it keeps getting hung up at the same spot.  The VMs turn on okay and get IP addresses, but when I run the command "ansible-playbook Testpoint-MaDDashbuild.yml -i hosts" it hangs at this point:

TASK [For ps & dj VMs, add perfsonar rpms to all testpoint edge nodes] ************************************************

I'm not for sure what is causing this to hang.  Any ideas?
Please let me know what kind of info you need from me.
Thanks!

**Comment by Brian-Tehan** [comment]
Turns out I didn't let this run long enough.  I let it go over an hour and the maddash UI is up now.  Closing this.

**Comment by preese** [comment]
Hi Brian,

Thanks for checking out the project, I think we can solve the issue.

I did a couple of installs this morning.   Turns out that the step, 
where you note a hang, actually may not be hanging after all!

In my tests, it took a full 5 minutes to show the first bit of feedback 
on that step in the Ansible Playbook.  Not exactly sure why, as it is 
only one install, 'prefsonar-testpoint'.  I think it is related to 
hitting a PS rpm archive with 6 demands at nearly the same time.

I did another test where I simply gathered together all the lines from 
github and pasted them into a freshly built Centos 7 box and hit 
return!  The full install, from start to finish took just under 16 min 
on my home network connection (which does have a pretty fast download 
speed, ~900Mbps).

Could I ask you to try running the ansible playbook again and just let 
it run and run and run?

I've a comment ready to publish which highlights that step may take a 
long time.

Please let me know either way if you can get past this issue.

Thanks,
Phil

**Comment by Brian-Tehan** [comment]
Hey Phil,

Yep, I let it run for over an hour or so in total and it finished successfully.  That part in particular was a little more than a half hour, I think.  I saw your update to the README.md file, thanks for adding that.

This was a good exercise for me to setup and use maddash, thanks for making this available.  A little bit of feedback for your consideration though:

I did a CenOS7 GUI install using gnome, instead of minimal, so that way it was easier to copy/paste commands from your github website into the terminal.
To make IP and MAC address changes, I used commands like this:  find ./ -type f -exec sed -i 's/192.164.1.21/192.168.4.24/g' {} \;
This is able to change all instances of a string in every file in a directory recursively and saved me some time.

Thanks!

Brian Tehan
Network Engineer | University of Nebraska ITS
Eppley Administration Building
6001 Dodge St EAB009F, Omaha, NE 68182-0051
402.554.6428 | ***@***.******@***.***>
